### PR TITLE
feat: add `find_own_input` helper

### PR DESCRIPTION
**Pull request by KristianBalaj**

### CODE REVIEW

**Comment by KristianBalaj** [comment]
@rvcas What do you think now? (regarding https://github.com/aiken-lang/stdlib/issues/45)

**Comment by rvcas** [comment]
@KristianBalaj come to the discord we're having a convo about this right now

**Comment by KtorZ** [comment]
Whoops. My apologies, I wrongly merged this PR while I intended to close it (and merge another). 

Following the conversations we've add on discord, we've collectively been voicing concerns about having such function in the stdlib. The main reasons being:

- This is very much PlutusTx / PlutusApi inspired, and Aiken is not PlutusApi. So while this may sound familiar for people that come from the Haskell framework, it is a bit weird for the others. 
- We prefer exposing people to the `ScriptPurpose` and having them know that they can extract information from it. Plus, given that the purpose may come in handy in other places, it'll be probably extracted and used outside of the function too.
- We opt for the smallest input domain possible when it comes to functions in the stdlib, to avoid doing double work in various places.

**Comment by KristianBalaj** [comment]
@KtorZ 

> We opt for the smallest input domain possible when it comes to functions in the stdlib, to avoid doing double work in various places.

Yup agreed, it's quantifiably better sending the smallest input domain.

> This is very much PlutusTx / PlutusApi inspired, and Aiken is not PlutusApi. So while this may sound familiar for people that come from the Haskell framework, it is a bit weird for the others.
We prefer exposing people to the ScriptPurpose and having them know that they can extract information from it. Plus, given that the purpose may come in handy in other places, it'll be probably extracted and used outside of the function too.

Okay, so you don't want to see the `find_own_input` in the stdlib at all, right? I don't agree with such a decision since factoring out logic is still a good practice for readability even for the price of a minor gain in performance if any performance gain at all. I personally prefer using `find_own_input` from some library than manually accessing script context and comparing it appropriately. It's also much more error prone. 
I judge based on my past experience writing OnChain code with PlutusTx where I use such a function quite often and it would be annoying if it would be missing in the stdlib.
The domain for PlutusTx and Aiken is still the same so it's natural that the code jargon will be similar.
In the end of the day it's your call, but I recommend to reconsider.

Could you please comment on the other mentioned functions here? https://github.com/aiken-lang/stdlib/issues/43
Whether they are also too much PlutusTX inspired (what's not a problem in my opinion) or you would accept them in the stdlib.

**Pull request merged**
