### PR TITLE
minted_value_to_dict

### PR DESCRIPTION
**Pull request by oskin1**

### CODE REVIEW

**Comment by KtorZ** [comment]
This is quite a foot gun, as this abstraction exists for a reason. 

May I ask what's the rationale for proposing this?

**Comment by oskin1** [comment]
I'd like to query quantity of minted assets without an extra operation (deletion of ada policy).
Also, in some cases I just want to check that some policy is present in the minted value (would be nice to avoid extra deletions here as well).
I'm ok with implementing the relevant methods in stdlib, just thought that simple unwrapping of the type will open the door for specific methods on the user site.

**Comment by KtorZ** [comment]
The deletion of the null Ada quantity is a cheap step (since it's always the first item in the dict) and thus makes every subsequent operations faster. 

I don't think you are really optimising anything here.

**Comment by MicroProofs** [comment]
Also MintedValue will be removed when we move Aiken to compile to PlutusV3. So just hang in there :)

**Pull request closed without merging**
