### PR TITLE
add a function to get the ada amount (if present) and the other values as a 2 tuple

### PR DESCRIPTION
**Pull request by MicroProofs**
simple straight forward function. Feel free to think of a better name

Helpful in cases like 

let (in_ada, other_in) = lovelace_and_other_values(input_value)

let (out_ada, other_out) = lovelace_and_other_values(output_value)

in_ada <= out_ada && other_in == other_out

### CODE REVIEW

**Comment by MicroProofs** [comment]
Fails on 1.0.7 but the issue was fixed for future version 1.0.8

**Comment by KtorZ** [comment]
Surely, we will need to do something about the name but, beyond that, I am failing to see the justification for that function? 

There are already ways to get the lovelace amount for a value pretty straightforwardly: 

```gleam
let lovelace = value.quantity_of(v, ada_policy_id, ada_asset_name)
let other = value.without_lovelace(v)
```

So this is a function that combines both but I am not even convinced it is that more efficient 😅 ?

**Comment by MicroProofs** [comment]
> Surely, we will need to do something about the name but, beyond that, I am failing to see the justification for that function?
> 
> There are already ways to get the lovelace amount for a value pretty straightforwardly:
> 
> ```gleam
> let lovelace = value.quantity_of(v, ada_policy_id, ada_asset_name)
> let other = value.without_lovelace(v)
> ```
> 
> So this is a function that combines both but I am not even convinced it is that more efficient 😅 ?

This is mostly convenience. I think it is slightly faster than using both those functions. So this is me more so arguing on this seems really useful to me for doing ada >= other_ada && value == other_value

**Comment by rvcas** [comment]
I see, seems cute. Let's think of a different name maybe?

**Comment by KtorZ** [comment]
Names suggestions:

- `split`
- `explode`

**Comment by rvcas** [comment]
Explode is cool

**Comment by MicroProofs** [comment]
Made some updates. Let me know what you think.

**Pull request closed without merging**
