### PR TITLE
Micah/generic hashing

### PR DESCRIPTION
**Pull request by micahkendall**

### CODE REVIEW

**Comment by rvcas** [comment]
I don't think this is gonna fly

**Comment by micahkendall** [comment]
It's more wieldable because you can hash anything. Considering the chooseData (which is relatively light), that's the job of the compiler, because this function can obviously be specialised down into zero-unnecessary-cost if optimisations are smart.

**Comment by rvcas** [comment]
Sure but I don't think it's hard or unreasonable to just expect people to serialize Data on their own. I don't see what usefulness this brings but that than just wrapping some stuff. If we did merge this I would rather have new functions instead of hijacking the existing ones. This existing ones are literally just to expose the builtins and I don't really want functions of that nature to do much else.

**Comment by KtorZ** [comment]
I am a bit on the fence on that one. One the one hand, I like the idea of it being a more general API with indeed a small overhead but that somewhat makes sense. Anything is serializable, so it sounds like this is the right API. Plus, it's unlikely that anyone would write their own serialization function by hand, given that the builtins CBOR-serialiser are already quite efficient. 

On the other hand, this is doing more work than necessary when one can just compose two functions together -- as Lucas says. 

Thing is, people who still want to compose can by simply using the builtin and in that sense, there's now at least an added value in using the stdlib. At the moment, I admittedly don't even use the stdlib myself for hashing and serializing because of the tiny overhead that comes compared to using raw builtins 😬 ... Because the builtins are so accessible and easy to use, I tend to use them directly in places where the stdlib provides no added value. Ultimately, that's a compiler optimization which should make this difference go away. 

We originally envisioned the stdlib also as a replacement for / superset of the builtins, so that people would not have to deal with builtins directly. But truth is, I still see a lot of direct usage of builtins especially for tasks like hashing or serialization. So, I tend to sit more on the side of "stdlib should provided an added value".

**Comment by rvcas** [comment]
I'm not sure if we're unwrapping the extra lambda on the builtin wrappers yet. @MicroProofs do you know? If so then there truly is not reason to use builtin module directly. But there's a lot of tiny decisions and concerns that overlap and I think that's ok. I tend to prefer as little abstraction as possible especially in Aiken.

**Comment by rvcas** [comment]
That all said if we do decide to go with this, at least we don't have to worry about backwards compat cause it takes anything now.

**Comment by MicroProofs** [comment]
> I'm not sure if we're unwrapping the extra lambda on the builtin wrappers yet. @MicroProofs do you know? If so then there truly is no reason to use the builtin module directly. But there's a lot of tiny decisions and concerns that overlap and I think that's ok. I tend to prefer as little abstraction as possible especially in Aiken.

Not yet but I have it planned soon.

**Comment by MicroProofs** [comment]
> It's more wieldable because you can hash anything. Considering the chooseData (which is relatively light), that's the job of the compiler, because this function can obviously be specialised down into zero-unnecessary-cost if optimisations are smart.

Unfortunately chooseData is the most costly builtin. Literally. Mostly due to taking 6 arguments.

Also at the compiler level we can't optimize chooseData since it literally is a branching statement. Unless we track what the data is beforehand which is a more hefty optimization to perform. And in some cases not possible like when using a datum from an input or output.

**Comment by MicroProofs** [comment]
The easier route in my opinion is use the hash function directly if you have a bytearray and use serialize data and then the hash for any form of Data or any other primitive

**Comment by MicroProofs** [comment]
I guess the question is should we have the normal hash functions for bytearray and also data specialized functions for serialization first?

**Comment by rvcas** [comment]
@MicroProofs I would prefer what you just said. Keep the current bytearray ones  and then add new ones for this generic case

**Pull request closed without merging**
