### PR TITLE
Adding reduce (left).

### PR DESCRIPTION
**Pull request by matiwinnetou**
Java and JavaScript developers are very used to reduce method such that it takes zero element first and appends in order all elements from left to right.

In order for them to feel more at home we are introducing reduce method.

Alternatively I can also write reduce_left and reduce_right.

### CODE REVIEW

**Comment by rvcas** [comment]
they can just use fold? I don't really see the point of adding this.

**Comment by matiwinnetou** [comment]
1. There is no foldl and foldr in java which is compatible with Aiken
2. One can write own foldl and foldr
3. In some cases order of elements matter (rare but still)

**Comment by rvcas** [comment]
@matiwinnetou we discussed this on discord, this kind of thing is something that should just always be confirmed by looking at the docs. Too many languages do too many slightly different things around this kind of function to even entertain "compatibility", in aiken we have `foldl` and `foldr`, full stop. JavaScript uses `reduce` that's cool, Rust uses `foldl` which also cool, Aiken has chosen `foldl` there's really nothing to solve here.

**Comment by matiwinnetou** [comment]
I think advice on reading documentation is pretty bad as many developers won't read docs.

**Comment by rvcas** [comment]
Well put that way and if reduce docs mention foldl then I could find this acceptable.

**Pull request closed without merging**
