### PR TITLE
new math function is_sqrt

### PR DESCRIPTION
**Pull request by francolq**

### CODE REVIEW

**Review by KtorZ — COMMENTED** [review]
Hey, thanks for the proposal but I am missing a bit the use case for such a function? Especially given that it requires both the square and the square root; so one could simply calculate the square of the root and compare it.

And it sounds sufficiently specific to perhaps not be in the stdlib? Am I missing something?

**Comment by francolq** [comment]
Thanks for the comment @KtorZ . The use case is when mem/cpu is an issue, for instance if sqrt of *very* big integers must be computed. In this case, instead of computing sqrt, it can be precomputed and provided from the off-chain code (for instance, through the redeemer), and on-chain it is only necessary to check for it using sqrt_is.

**Comment by rvcas** [comment]
I would flip the words in the name so that it's instead: `is_sqrt`

**Comment by francolq** [comment]
I just did the renaming to is_sqrt and fixed the formatting to pass the aiken fmt check.

**Comment by micahkendall** [comment]
Why not `x*x==self && x>=0` ?

**Comment by francolq** [comment]
> Why not `x*x==self && x>=0` ?

Because is_sqrt is the counterpart of sqrt where the integer part of the square root is computed. For instance, `sqrt(44203) == Some(210)`, so we want `is_sqrt(44203, 210)` to return True.

**Comment by KtorZ** [comment]
I am still not quite convinced that this function belongs to the stdlib 😕. It sounds rather use-case specific to me.

**Comment by francolq** [comment]
No problem, I'll do a last try to convince:

1. "is_sqrt" should be preferred over "sqrt" every time it is possible. Sometimes the square root value is already available, for instance as a quantity of an output asset.
In these cases, it makes no sense to compute the sqrt again and then compare with equality.

2. The "sqrt" / "is_sqrt" duality illustrates the fact that sometimes checking is much cheaper than calculating. This fact, together with the possibility of providing "helper" values calculated off-chain, configure a design pattern that enables the implementation of complex business logics that would be impossible otherwise. Actually, this PR is a result of the experience I had implementing a real world dapp (see next item).

3. For my work I had to compute several nth roots (more general than sqrt), so I defined a "nth_root" function that uses a sort of binary search. However I saw that it was too expensive in mem/cpu (at least for our use case), so I had to define "is_nth_root" and provide the helper values through the redeemer. My guess is that most developers that need the nth root in a realistic scenario will have to do the same. I was expecting to collaborate a PR with "nth_root" / "is_nth_root"" soon, but for me it made sense to first have "sqrt" / "is_sqrt".

**Comment by Quantumplation** [comment]
I would also like to see this in the stdlib, as it encourages / reveals the good practice of checking with is_sqrt over computing it directly. Though, in that case, I would recommend beefing up the documentation on is_sqrt and sqrt to explain why you might prefer is_sqrt, to make that pattern more discoverable to people.

Also, as a side note, I did some benchmarking of these two implementations to see if I could save some redundant calcs, and it did not, so I thought I would record for posterity:
```
baseline:
    │ PASS [mem:   3811, cpu:   1945206] is_sqrt1
    │ PASS [mem:   3811, cpu:   1945206] is_sqrt2
```

```
pub fn is_sqrt(self: Int, x: Int) -> Bool {
  x*x <= self && x*x + 2*x + 1 > self
}

    │ PASS [mem:   4213, cpu:   2130102] is_sqrt1
    │ PASS [mem:   4213, cpu:   2130102] is_sqrt2
```

```
pub fn is_sqrt(self: Int, x: Int) -> Bool {
  let x_sq = x*x
  let two_x = 2 * x
  x_sq <= self && x_sq + two_x + 1 > self
}


    │ PASS [mem:   4411, cpu:   2083206] is_sqrt1
    │ PASS [mem:   4411, cpu:   2083206] is_sqrt2
```

**Review by KtorZ — APPROVED** [review]

**Pull request merged**
